import { type Config } from "tailwindcss";

export default <Config>{
  content: ["./index.html", "./src/**/*.{ts,tsx,js,jsx}"],
  theme: {
    extend: {
      colors: {
        background: "var(--background)",
        foreground: "var(--foreground)",
        card: "var(--card)",
        "card-foreground": "var(--card-foreground)",
        popover: "var(--popover)",
        "popover-foreground": "var(--popover-foreground)",
        primary: "var(--primary)",
        "primary-foreground": "var(--primary-foreground)",
        secondary: "var(--secondary)",
        "secondary-foreground": "var(--secondary-foreground)",
        muted: "var(--muted)",
        "muted-foreground": "var(--muted-foreground)",
        accent: "var(--accent)",
        "accent-foreground": "var(--accent-foreground)",
        destructive: "var(--destructive)",
        "destructive-foreground": "var(--destructive-foreground)",
        border: "var(--border)",
        input: "var(--input)",
        "input-background": "var(--input-background)",
        "switch-background": "var(--switch-background)",
        ring: "var(--ring)",
        "chart-1": "var(--chart-1)",
        "chart-2": "var(--chart-2)",
        "chart-3": "var(--chart-3)",
        "chart-4": "var(--chart-4)",
        "chart-5": "var(--chart-5)",
        sidebar: "var(--sidebar)",
        "sidebar-foreground": "var(--sidebar-foreground)",
        "sidebar-primary": "var(--sidebar-primary)",
        "sidebar-primary-foreground": "var(--sidebar-primary-foreground)",
        "sidebar-accent": "var(--sidebar-accent)",
        "sidebar-accent-foreground": "var(--sidebar-accent-foreground)",
        "sidebar-border": "var(--sidebar-border)",
        "sidebar-ring": "var(--sidebar-ring)",
        "electric-blue": "var(--electric-blue)",
        "brand-red": "var(--brand-red)",
        "brand-cream": "var(--brand-cream)",
        "brand-blue": "var(--brand-blue)",
        "dark-bg": "var(--dark-bg)",
        "dark-surface": "var(--dark-surface)",
        "dark-elevated": "var(--dark-elevated)",
      },
      borderRadius: {
        sm: "calc(var(--radius) - 4px)",
        md: "calc(var(--radius) - 2px)",
        lg: "var(--radius)",
        xl: "calc(var(--radius) + 4px)",
      },
      fontSize: {
        base: "var(--font-size)",
        "text-lg": "var(--text-lg)",
        "text-xl": "var(--text-xl)",
        "text-2xl": "var(--text-2xl)",
      },
      fontWeight: {
        normal: "var(--font-weight-normal)",
        medium: "var(--font-weight-medium)",
      },
      outline: {
        DEFAULT: ["var(--ring)", "1px solid"],
      },
      borderWidth: {
        DEFAULT: "1px",
      },
    },
  },
  darkMode: ["class", '[data-theme="dark"]'], // kompatybilne z .dark
  plugins: [],
  safelist: [
    // dodaj wszystkie klasy z Figma, które są niestandardowe
    "h-13",
    "w-13",
    "text-wrapper-7",
    "frame-12",
    "bg-[#0c1b2a]",
    "bg-[#152030]",
    "text-[#faf6ef]",
    "text-[#c30406]",
    "bg-[#c30406]",
    "hover:bg-[#a50305]",
    "hover:shadow-[#c30406]/20",
    "border-white/10",
    "backdrop-blur-xl",
    "rounded-lg",
    "object-cover",
    "group-hover:scale-105",
    "transition-transform",
    "transition-colors",
    "absolute",
    "bottom-0",
    "left-0",
    "right-0",
    "h-0.5",
  ],
};
